import * as THREE from 'three';
import { PlanetType } from './@types';

export const planets: PlanetType[] = [
  {
    name: "space",
    mapImagePath: "stars_milky_way.jpg",
    scaleFactor: 1000,
    position: new THREE.Vector3(0, 0, 0),
    groupPosition: new THREE.Vector3(0, 0, 0),
    rotationFactor: 0.1,
    revolutionFactor: 0,
  },
  {
    name: "sun",
    mapImagePath: "sun.jpg",
    scaleFactor: 109,
    position: new THREE.Vector3(0, 0, 0),
    groupPosition: new THREE.Vector3(0, 0, 0),
    rotationFactor: 1 / 27,
    revolutionFactor: 0,
  },
  {
    name: "mercury",
    mapImagePath: "mercury.jpg",
    scaleFactor: 0.33,
    position: new THREE.Vector3(150, 0, -0.387),
    groupPosition: new THREE.Vector3(0, 0, 0),
    rotationFactor: 10.83 / 1574,
    revolutionFactor: 1.59,
  },
  {
    name: "venus",
    mapImagePath: "venus.jpg",
    scaleFactor: 0.949,
    position: new THREE.Vector3(-190, 10, -0.723),
    groupPosition: new THREE.Vector3(0, 0, 0),
    rotationFactor: -6.52 / 1574,
    revolutionFactor: 1.18,
  },
  {
    name: "earth",
    mapImagePath: "earth.jpg",
    specMapImagePath: "earth_specmap.jpg",
    normalMapImagePath: "earth_normalmap.jpg",
    normalScale: new THREE.Vector2(0.5, 0.7),
    specular: new THREE.Color(0x262626),
    scaleFactor: 1,
    position: new THREE.Vector3(220, 0, -1),
    groupPosition: new THREE.Vector3(0, 0, 0),
    rotationFactor: 1,
    revolutionFactor: 1,
    hasMoon: true,
    moons: [
      {
        name: "clouds",
        mapImagePath: "earth_clouds.png",
        scaleFactor: 1.005,
        position: new THREE.Vector3(220, 0, -1),
        groupPosition: new THREE.Vector3(0, 0, 0),
        rotationFactor: 1,
        revolutionFactor: 0,
        transparent: true,
      },
      {
        name: "moon",
        mapImagePath: "moon.jpg",
        scaleFactor: 0.2724,
        position: new THREE.Vector3(5, 0, -1.00257),
        groupPosition: new THREE.Vector3(220, 0, -1),
        rotationFactor: 1 / 27.32,
        revolutionFactor: 0.0343,
      },
    ],
  },
  {
    name: "mars",
    mapImagePath: "mars.jpg",
    scaleFactor: 0.532,
    position: new THREE.Vector3(-260, 0, -1.52),
    groupPosition: new THREE.Vector3(0, 0, 0),
    rotationFactor: 866 / 1574,
    revolutionFactor: 0.808,
  },
  {
    name: "jupiter",
    mapImagePath: "jupiter.jpg",
    scaleFactor: 11.21,
    position: new THREE.Vector3(355, 0, -5.2),
    groupPosition: new THREE.Vector3(0, 0, 0),
    rotationFactor: 45583 / 1574,
    revolutionFactor: 0.439,
  },
  {
    name: "saturn",
    mapImagePath: "saturn.jpg",
    scaleFactor: 9.45,
    position: new THREE.Vector3(-450, -10, -9.57),
    groupPosition: new THREE.Vector3(0, 0, 0),
    rotationFactor: 36840 / 1574,
    revolutionFactor: 0.325,
    hasRing: true,
    rings: [
      {
        name: "saturn-ring",
        mapImagePath: "saturn_ring1.png",
        innerRadius: 10,
        outerRadius: 20,
        rotationX: Math.PI / 2,
        rotationY: Math.PI / 8,
      },
    ],
  },
  {
    name: "uranus",
    mapImagePath: "uranus.jpg",
    scaleFactor: 4.01,
    position: new THREE.Vector3(600, 10, -19.17),
    groupPosition: new THREE.Vector3(0, 0, 0),
    rotationFactor: -14794 / 1574,
    revolutionFactor: 0.228,
    hasRing: true,
    rings: [
      {
        name: "uranus-ring",
        mapImagePath: "uranus_ring.png",
        innerRadius: 7,
        outerRadius: 12,
        rotationX: Math.PI / 2,
        rotationY: 0,
      },
    ],
  },
  {
    name: "neptune",
    mapImagePath: "neptune.jpg",
    scaleFactor: 3.88,
    position: new THREE.Vector3(-650, 30, -30.18),
    groupPosition: new THREE.Vector3(0, 0, 0),
    rotationFactor: 9719 / 1574,
    revolutionFactor: 0.182,
    hasRing: true,
    rings: [
      {
        name: "neptune-ring1",
        mapImagePath: "neptune_ring2.png",
        innerRadius: 7,
        outerRadius: 7.2,
        rotationX: Math.PI / 2,
        rotationY: 0,
        alphaImagePath: "neptune_ring_alpha2.jpg",
        transparent: true,
      },
      {
        name: "neptune-ring2",
        mapImagePath: "neptune_ring2.png",
        innerRadius: 7,
        outerRadius: 9.2,
        rotationX: Math.PI / 2,
        rotationY: 0,
        alphaImagePath: "neptune_ring_alpha2.jpg",
        transparent: true,
      },
      {
        name: "neptune-ring3",
        mapImagePath: "neptune_ring2.png",
        innerRadius: 10,
        outerRadius: 10.2,
        rotationX: Math.PI / 2,
        rotationY: 0,
        alphaImagePath: "neptune_ring_alpha2.jpg",
        transparent: true,
      },
    ],
  },
];

// https://nssdc.gsfc.nasa.gov/planetary/factsheet/planet_table_ratio.html
